export const products = [
  {
    id: 'bogarvaros',
    name: 'Bogárváros',
    description: 'Egyedi digitális illusztráció — azonnali letöltés',
    price: 350000,
    currency: 'huf',
    image: null,
  },
  {
    id: 'esogyujtes',
    name: 'Esőgyűjtés',
    description: 'Egyedi digitális illusztráció — azonnali letöltés',
    price: 350000,
    currency: 'huf',
    image: null,
  },
  {
    id: 'cseresznye-hinta',
    name: 'Cseresznye hinta',
    description: 'Egyedi digitális illusztráció — azonnali letöltés',
    price: 350000,
    currency: 'huf',
    image: null,
  },
  {
    id: 'kempingezés',
    name: 'Kempingezés',
    description: 'Egyedi digitális illusztráció — azonnali letöltés',
    price: 350000,
    currency: 'huf',
    image: null,
  },
  {
    id: 'norveg-mese',
    name: 'Norvég mese',
    description: 'Egyedi digitális illusztráció — azonnali letöltés',
    price: 350000,
    currency: 'huf',
    image: null,
  },
  {
    id: 'esoben-hazafele',
    name: 'Esőben hazafele',
    description: 'Egyedi digitális illusztráció — azonnali letöltés',
    price: 350000,
    currency: 'huf',
    image: null,
  },
  {
    id: 'tea-a-csillagok-alatt',
    name: 'Tea a csillagok alatt',
    description: 'Egyedi digitális illusztráció — azonnali letöltés',
    price: 350000,
    currency: 'huf',
    image: null,
  },
  {
    id: 'naplemente',
    name: 'Naplemente',
    description: 'Egyedi digitális illusztráció — azonnali letöltés',
    price: 350000,
    currency: 'huf',
    image: null,
  },
];
